version: '3.9'

services:
  flask_app:
    build: .
    ports:
      - "4000:5000"
    environment:
      - CONNECTION_STRING=Driver={ODBC Driver 17 for SQL Server};Server=mssql_db,1433;Database=Flask_SF;Uid=sa;Pwd=Engraciacosme-123;
    depends_on:
      - mssql_db

  mssql_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1432"
    environment:
      SA_PASSWORD: "Engraciacosme-123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlserver & 
      sleep 30s && 
      /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Engracia-cosme123' -i /docker-entrypoint-initdb.d/init.sql
      "
volumes:
  mssql_data:
